"use client";
import { ThemeProvider } from "@mui/material";
import { Inter } from "next/font/google";
import { lightTheme } from "../../themes";
import "../../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={lightTheme}>
        <body className={inter.className}>
          <h1>Navbar</h1>
          {children}
          <h1>Footer</h1>
        </body>
      </ThemeProvider>
    </html>
  );
}
